global using MealMate.ViewModels;
global using CommunityToolkit.Mvvm.Input;
global using MealMate.View;
global using MealMate.Models;
global using MealMate.Services;
global using System.Diagnostics;
global using MealMate.Services.Interfaces;
global using System.Net.Http.Json;
global using CommunityToolkit.Mvvm.ComponentModel;
